replicaCount: 2

secretName: welend-site3-secret
env:
  normal:
    NODE_ENV: production
    PORT: 8888
    API_HOST: https://member.welend.hk
    APPLICATION_FORM_BASE: https://app.welend.hk
    SITE_URL: https://www.welend.hk
    AHOY_URL: //pepsi.welend.hk
    AHOY_COOKIE_DOMAIN: welend.hk
    CAMPAIGN_VIDEO_LINK: yl27InbB7ks
    FB_APP_ID: 1597382100498095
    SAKE_URL: https://member.welend.hk
    STATIC_API_HOST: https://api.welend.hk
    BUGSNAG_PUBLIC_PATH: https://www.welend.hk
    MONEY_LENDER_LICENSE: 0970 / 2021
    CAMPAIGN_VIDEO_LINK2: Uifzmnfj4kM
    WELAB_BANK_URL: https://welab.bank
    PROMO_END: 2020-06-30
    NOTICE_TYPE: Relocation2020
    NOTICE_START_TIME: 2020-05-04T00:00:00+08:00
    NOTICE_END_TIME: 2020-05-31T23:59:00+08:00
  secret:
    API_CLIENT_ID: data_from_vault
    API_CLIENT_SECRET: data_from_vault
    BOTFRAMEWORK_SECRET: data_from_vault
    BUGSNAG_KEY: data_from_vault
    GTM: data_from_vault
  wl7615:
    default.conf: |
      server {    listen       80;    server_name  localhost;    location / {        root   /usr/share/nginx/html;        index  index.html index.htm;    }    location ^~ /aiblog/ {        proxy_set_header X-Real-IP $remote_addr;        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;        proxy_set_header X-NginX-Proxy true;        proxy_pass https://54.151.254.137/;        proxy_ssl_verify off; proxy_ssl_session_reuse off;        proxy_set_header Host aiblog.welend.hk;        proxy_cache_bypass $http_upgrade;        proxy_redirect off;    }    location /internal/ping {        return 200 'OK';    }   }server {    listen       80;    server_name  welend-site3-aiblog.prod.welend.local welend-site3-aiblog.sta.welend.local welend-site3-aiblog.dev.welend.local;    location ^~ /aiblog/ {        proxy_set_header X-Real-IP $remote_addr;        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;        proxy_set_header X-NginX-Proxy true;        proxy_pass https://54.151.254.137/;        proxy_ssl_verify off; proxy_ssl_session_reuse off;        proxy_set_header Host aiblog.welend.hk;        proxy_cache_bypass $http_upgrade;        proxy_redirect off;    } location /internal/ping {        return 200 'OK';    }      location / {        return 301 https://www.welend.hk/aiblog$request_uri;    }}

image:
  pullPolicy: Always

serviceAccount:
  create: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: kong
  hosts:
    - host: welend-site3.prod.welend.local
      paths:
        - path: /aiblog
          service: welend-site3-wl7615
        - path: /
          service: welend-site3
    - host: welend-site3-aiblog.prod.welend.local
      paths:
        - path: /
          service : welend-site3-wl7615
  tls:
    - hosts:
        - welend-site3.prod.welend.local
        - welend-site3-aiblog.prod.welend.local
      secretName: welend-site3-tls-secret-20230427

resources:
  requests:
    cpu: "250m"
  limits:
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  wl7615enabled: true
  wl7615minReplicas: 3
  wl7615maxReplicas: 10
  wl7615targetCPUUtilizationPercentage: 50