const routes = require('next-routes');

module.exports = routes()
    .add("home", "/:locale(tc|en)?")
    .add("about-us", "/:locale(tc|en)?/about-us")
    .add("card-debt-tips", "/:locale(tc|en)?/card-debt-tips")
    .add("contact-us", "/:locale(tc|en)?/contact-us")
    .add("faqs", "/:locale(tc|en)?/faqs")
    .add("how-it-work", "/:locale(tc|en)?/how-it-work")
    .add("important-notice", "/:locale(tc|en)?/important-notice")
    .add("money-lenders-ordinance", "/:locale(tc|en)?/money-lenders-ordinance")
    .add("payment-methods", "/:locale(tc|en)?/payment-methods")
    .add("privacy-policy", "/:locale(tc|en)?/privacy-policy")
    .add("customer-declaration", "/:locale(tc|en)?/customer-declaration")
    .add("products", "/:locale(tc|en)?/products")
    .add("products/3hk", "/:locale(tc|en)?/products/3hk")
    .add("products/balance-transfer", "/:locale(tc|en)?/products/balance-transfer")
    .add("products/balance-transfer-calculator", "/:locale(tc|en)?/products/balance-transfer#calculator")
    .add("products/no-doc-loan", "/:locale(tc|en)?/products/no-doc-loan")
    .add("products/personal-loan", "/:locale(tc|en)?/products/personal-loan")
    .add("products/property-owner-loan", "/:locale(tc|en)?/products/property-owner-loan")
    .add("quotes", "/:locale(tc|en)?/quotes")
    .add("webot-web", "/webot-web")
    .add("gift-redemption", "/:locale(tc)/gift-redemption")
    .add("logout-callback", "/logout/callback")
    .add("osaka-game-tnc", "/osaka-game-tnc")
    .add("declaration-cashloan", "/:locale(tc|en)?/declaration-cashloan")
    .add("terms-and-conditions","/:locale(tc|en)?/terms-and-conditions")
