version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Use Yarn
          command: sudo npm install -g yarn --force
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Lint
          command: yarn lint
      - run:
          name: Run Test
          command: yarn test --maxWorkers=2
    docker:
      - image: circleci/node:10
